package TrafficLegacy;


/**
* TrafficLegacy/_TrafficControllerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/traffic/corba/TrafficLight.idl
* Friday, December 5, 2025 1:51:41 PM WAT
*/

public class _TrafficControllerStub extends org.omg.CORBA.portable.ObjectImpl implements TrafficLegacy.TrafficController
{


  // 0 = RED, 1 = GREEN, 2 = ORANGE
  public String setSignalState (String junctionId, int state)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setSignalState", true);
                $out.write_string (junctionId);
                $out.write_long (state);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return setSignalState (junctionId, state        );
            } finally {
                _releaseReply ($in);
            }
  } // setSignalState

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TrafficLegacy/TrafficController:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _TrafficControllerStub
