package TrafficLegacy;


/**
* TrafficLegacy/TrafficControllerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/traffic/corba/TrafficLight.idl
* Friday, December 5, 2025 1:51:41 PM WAT
*/

abstract public class TrafficControllerHelper
{
  private static String  _id = "IDL:TrafficLegacy/TrafficController:1.0";

  public static void insert (org.omg.CORBA.Any a, TrafficLegacy.TrafficController that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TrafficLegacy.TrafficController extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TrafficLegacy.TrafficControllerHelper.id (), "TrafficController");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TrafficLegacy.TrafficController read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TrafficControllerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TrafficLegacy.TrafficController value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TrafficLegacy.TrafficController narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TrafficLegacy.TrafficController)
      return (TrafficLegacy.TrafficController)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TrafficLegacy._TrafficControllerStub stub = new TrafficLegacy._TrafficControllerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TrafficLegacy.TrafficController unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TrafficLegacy.TrafficController)
      return (TrafficLegacy.TrafficController)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TrafficLegacy._TrafficControllerStub stub = new TrafficLegacy._TrafficControllerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
