package TrafficLegacy;

/**
* TrafficLegacy/TrafficControllerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/traffic/corba/TrafficLight.idl
* Friday, December 5, 2025 1:51:41 PM WAT
*/

public final class TrafficControllerHolder implements org.omg.CORBA.portable.Streamable
{
  public TrafficLegacy.TrafficController value = null;

  public TrafficControllerHolder ()
  {
  }

  public TrafficControllerHolder (TrafficLegacy.TrafficController initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TrafficLegacy.TrafficControllerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TrafficLegacy.TrafficControllerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TrafficLegacy.TrafficControllerHelper.type ();
  }

}
