package TrafficLegacy;


/**
* TrafficLegacy/TrafficControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/traffic/corba/TrafficLight.idl
* Friday, December 5, 2025 1:51:41 PM WAT
*/

public interface TrafficControllerOperations 
{

  // 0 = RED, 1 = GREEN, 2 = ORANGE
  String setSignalState (String junctionId, int state);
} // interface TrafficControllerOperations
