package TrafficLegacy;


/**
* TrafficLegacy/TrafficController.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/traffic/corba/TrafficLight.idl
* Friday, December 5, 2025 1:51:41 PM WAT
*/

public interface TrafficController extends TrafficControllerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TrafficController
