package TrafficLegacy;


/**
* TrafficLegacy/TrafficControllerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from com/traffic/corba/TrafficLight.idl
* Friday, December 5, 2025 1:51:41 PM WAT
*/

public abstract class TrafficControllerPOA extends org.omg.PortableServer.Servant
 implements TrafficLegacy.TrafficControllerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("setSignalState", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // 0 = RED, 1 = GREEN, 2 = ORANGE
       case 0:  // TrafficLegacy/TrafficController/setSignalState
       {
         String junctionId = in.read_string ();
         int state = in.read_long ();
         String $result = null;
         $result = this.setSignalState (junctionId, state);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TrafficLegacy/TrafficController:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TrafficController _this() 
  {
    return TrafficControllerHelper.narrow(
    super._this_object());
  }

  public TrafficController _this(org.omg.CORBA.ORB orb) 
  {
    return TrafficControllerHelper.narrow(
    super._this_object(orb));
  }


} // class TrafficControllerPOA
